### ISSUE TITLE
Guidance Page: sizing fixed boxes

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website-gatsby#28] opened 2018-09-14 02:39 UTC
A user needs to understand the sizing recommendation of fixed boxes.

DESIGN
- [ ] Sizing Fixed Boxes using Size Scales (box equivalent to Type Scales) and Aspect Ratios
- [ ] written content explanation
- [ ] design of guidelines on page

DEVELOPMENT
- [ ] link to content (v1)
- [ ] inline documentation on page (v2)

**Comment by kuehndaniel** [comment] 2018-09-17 22:07
closing this issue as it's a duplicate of: https://github.com/carbon-design-system/carbon-website-gatsby/issues/25

**Closed by kuehndaniel** 2018-09-17 22:07 UTC
Labels: project: website, type: docs :book:
