### ISSUE TITLE
Guidance Page: page geometry

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website-gatsby#31] opened 2018-09-14 02:42 UTC
A user needs to understand an abstracted shell showing high level regions (header, navigation, panels etc.).

DESIGN
- [ ] reference Page Geometry (Regions) design work
- [ ] written content explanation
- [ ] design of guidelines on page

DEVELOPMENT
- [ ] link to content (v1)
- [ ] inline documentation on page (v2)

**Comment by kuehndaniel** [comment] 2018-09-17 22:07
closing this issue as it's a duplicate of: https://github.com/carbon-design-system/carbon-website-gatsby/issues/25

**Closed by kuehndaniel** 2018-09-17 22:07 UTC
Labels: project: website, type: docs :book:
